#! /bin/sh

setxkbmap de &
light-locker &
$HOME/.config/scripts/display.sh
nitrogen --restore
wal -R
python	/home/noventicx/.config/scripts/razerwal.py
python  /home/noventicx/.config/scripts/hue-wal.py
xsetroot -cursor_name left_ptr
picom -f &
dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

lxsession &

bspc config external_rules_command "$HOME/.config/scripts/spotifywm"

$HOME/.config/scripts/bspswallow &

$HOME/.config/scripts/cleanfullscreen &

$HOME/.config/scripts/lock &

$HOME/.local/lib/python3.9/site-packages/pywalfox/bin/main.sh &

$HOME/.config/polybar/launch.sh

echo "export _JAVA_AWT_WM_NONREPARENTING=1" >> /etc/profile.d/jre.sh

bspc monitor "HDMI-1" -d I II III

bspc monitor "DP-2" -d IV V VI

bspc monitor "DP-0" -d VII VIII IX

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreWolf desktop='^5'
bspc rule -a Thunderbird desktop='^6'
#bspc rule -a jetbrains-idea desktop='^4'
bspc rule -a "" desktop='^1'
bspc rule -a discord desktop='^7'

bspc rule -a origin.exe state=floating

bspc rule -a Zathura state=tiled

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Yubico Authenticator" state=floating

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
